//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.6
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Home</summary>
	[PublishedModel("home")]
	public partial class Home : PublishedContentModel, IContentBase
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const string ModelTypeAlias = "home";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Home(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// DANH SÁCH KHÁCH SẠN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("allHotels")]
		public Newtonsoft.Json.Linq.JToken AllHotels => this.Value<Newtonsoft.Json.Linq.JToken>("allHotels");

		///<summary>
		/// HÌNH ẢNH NỀN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cncBackground")]
		public IEnumerable<IPublishedContent> CncBackground => this.Value<IEnumerable<IPublishedContent>>("cncBackground");

		///<summary>
		/// NỘI DUNG
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cncDescription")]
		public string CncDescription => this.Value<string>("cncDescription");

		///<summary>
		/// TIÊU ĐỀ
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("cncHeader")]
		public string CncHeader => this.Value<string>("cncHeader");

		///<summary>
		/// NỘI DUNG
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("galleryBody")]
		public string GalleryBody => this.Value<string>("galleryBody");

		///<summary>
		/// HÌNH ẢNH
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("galleryImages")]
		public IEnumerable<Umbraco.Core.Models.MediaWithCrops> GalleryImages => this.Value<IEnumerable<Umbraco.Core.Models.MediaWithCrops>>("galleryImages");

		///<summary>
		/// TIÊU ĐỀ
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("galleryTitle")]
		public string GalleryTitle => this.Value<string>("galleryTitle");

		///<summary>
		/// HÌNH ẢNH CHÍNH
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("landscapeImages")]
		public IEnumerable<IPublishedContent> LandscapeImages => this.Value<IEnumerable<IPublishedContent>>("landscapeImages");

		///<summary>
		/// DANH SÁCH KHÁCH SẠN
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("nhtBodyText")]
		public Newtonsoft.Json.Linq.JToken NhtBodyText => this.Value<Newtonsoft.Json.Linq.JToken>("nhtBodyText");

		///<summary>
		/// PROMOTION PHOTO
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("promotionPhoto")]
		public Umbraco.Core.Models.MediaWithCrops PromotionPhoto => this.Value<Umbraco.Core.Models.MediaWithCrops>("promotionPhoto");

		///<summary>
		/// PROMOTION URL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("promotionUrl")]
		public string PromotionUrl => this.Value<string>("promotionUrl");

		///<summary>
		/// Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("bodyText")]
		public Newtonsoft.Json.Linq.JToken BodyText => ContentBase.GetBodyText(this);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.6")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => ContentBase.GetPageTitle(this);
	}
}
